modLoader="javafml"
loaderVersion="[25,)"
license="CC0-1.0"
issueTrackerURL="https://example.invalid/"
displayTest="IGNORE_ALL_VERSION"

[[mods]]
modId="test_multi_project_mod_please_ignore"
version="${file.jarVersion}"
displayName="Test Multi-Project Mod Please Ignore"
description="Test multi-project mod"
authors="3TUSK"

[[dependencies.test_multi_project_mod_please_ignore]]
modId="minecraft"
mandatory=true
versionRange="[1.19.3]"